# Generated by Django 3.2.15 on 2022-09-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='songs',
            name='composer',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
